variable "project_id" {type = string}
variable "region" {type = string}
# variable "zone" {type = string}
# variable "instance_name" {type = string}
# variable "machine_type" {type = string}
# variable "backend_instance_name" {type = string}
# variable "backend_machine_type" {type = string}
# variable "backend_zone" {type = string}
# variable "subnet_name" {type = string}
# variable "network_name" {type = string}
# variable "subnet_cidr" {type = string}
# variable "network_cidr" {type = string}
# variable "firewall_name" {type = string}
# variable "firewall_ports" {type = list(string)}
# variable "firewall_source_ranges" {type = list(string)}
# variable "backend_subnet_name" {type = string}
# variable "backend_subnet_cidr" {type = string}
# variable "region_2" {type = string}
variable "env_prefix" {type = string}